// <auto-generated />
namespace Prover.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addjobid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addjobid));
        
        string IMigrationMetadata.Id
        {
            get { return "201611070412573_add job-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
