// <auto-generated />
namespace Prover.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddClientItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClientItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201612301400385_AddClientItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
