// <auto-generated />
namespace Prover.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class pressuretests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pressuretests));
        
        string IMigrationMetadata.Id
        {
            get { return "201603040557172_pressure-tests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
