// <auto-generated />
namespace Prover.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFrequencyTests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFrequencyTests));
        
        string IMigrationMetadata.Id
        {
            get { return "201711250153353_Add-FrequencyTests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
