// <auto-generated />
namespace Prover.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMasterSlavegroupings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMasterSlavegroupings));
        
        string IMigrationMetadata.Id
        {
            get { return "201810140347400_Add-Master-Slave-groupings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
